-- CreateTable
CREATE TABLE "Post" (
    "POST_ID" TEXT NOT NULL,
    "DATA" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DESCRICAO" TEXT,
    "userId" TEXT NOT NULL,

    CONSTRAINT "Post_pkey" PRIMARY KEY ("POST_ID")
);

-- AddForeignKey
ALTER TABLE "Post" ADD CONSTRAINT "Post_POST_ID_fkey" FOREIGN KEY ("POST_ID") REFERENCES "users"("USER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
